using FlyingGame.Core;
using FlyingGame.Core.DataContracts;
using FlyingGame.Sim.Practice;
using Xunit;
using Xunit.Abstractions;

namespace FlyingGame.FlightTests;

/// <summary>The idle-glide table (owner 2026-10-03) and the new-airplane protocol's automated checks
/// (docs/NEW-AIRPLANE-PROTOCOL.md). Regenerate after changing any aircraft: REGEN_GLIDE_TABLE=1 dotnet test --filter GlideTable</summary>
public class GlideTableTests
{
    private readonly ITestOutputHelper _o;
    public GlideTableTests(ITestOutputHelper o) { _o = o; }

    private static string Repo
    {
        get { var d = new DirectoryInfo(AppContext.BaseDirectory); while (d != null && !Directory.Exists(Path.Combine(d.FullName, "configs", "aircraft"))) d = d.Parent; return d!.FullName; }
    }
    private static IEnumerable<AircraftConfig> All() =>
        Directory.GetFiles(Path.Combine(Repo, "configs", "aircraft"), "*.json").OrderBy(f => f).Select(AircraftConfigLoader.LoadFromFile);

    [Fact]
    public void GlideTableIsCurrentForEveryAircraftAndFlapSetting()
    {
        var rows = new List<GlideEntry>();
        foreach (AircraftConfig c in All()) foreach (double f in GlideTable.FlapSettings(c)) rows.Add(GlideTable.Round(GlideTable.Compute(c, f)));
        string jsonPath = Path.Combine(Repo, "configs", "glide-table.json");
        if (Environment.GetEnvironmentVariable("REGEN_GLIDE_TABLE") != null)
        {
            File.WriteAllText(jsonPath, GlideTable.ToJson(rows));
            File.Copy(jsonPath, Path.Combine(Repo, "unity", "Assets", "StreamingAssets", "glide-table.json"), true);
            var md = new System.Text.StringBuilder();
            md.AppendLine("# Idle glide table — 1.3 Vso, engine at idle (generated)\n");
            md.AppendLine("Owner 2026-10-03. Every landing lesson starts on its row: idle, on speed, trimmed. Generated by");
            md.AppendLine("`REGEN_GLIDE_TABLE=1 dotnet test --filter GlideTable` from the configs; `GlideTableTests` fails if it is stale.");
            md.AppendLine($"Valley field ({WorldTerrain.DatumM * 3.28084:F0} ft), windmilling-prop drag included; gliders at half spoiler.\n");
            md.AppendLine("| Aircraft | Flaps | Vso kt | 1.3 Vso kt | Glide ° | Ratio | Sink fpm | Pitch ° | AoA ° | Elevator ° | Trim (stick) |");
            md.AppendLine("|---|---|---|---|---|---|---|---|---|---|---|");
            foreach (var r in rows) md.AppendLine($"| {r.Id} | {(r.Flaps == 0 ? "up" : r.Flaps < 0.9 ? "half" : "full")} | {r.VsoKt:F0} | {r.SpeedKt:F0} | {r.GlideDeg:F1} | {r.GlideRatio:F1}:1 | {r.SinkFpm:F0} | {r.PitchDeg:F1} | {r.AlphaDeg:F1} | {r.ElevatorDeg:F1} | {r.TrimStick:+0.00;-0.00} |");
            File.WriteAllText(Path.Combine(Repo, "docs", "GLIDE-TABLE.md"), md.ToString());
        }
        Assert.True(File.Exists(jsonPath), "configs/glide-table.json missing — run REGEN_GLIDE_TABLE=1");
        GlideTable.LoadJson(File.ReadAllText(jsonPath));
        foreach (var r in rows)
        {
            GlideEntry? t = GlideTable.Lookup(r.Id, r.Flaps);
            Assert.True(t != null, $"{r.Id} flaps {r.Flaps} not in the glide table — run REGEN_GLIDE_TABLE=1 (new-airplane protocol)");
            Assert.True(Math.Abs(t!.SpeedKt - r.SpeedKt) < 0.5 && Math.Abs(t.GlideDeg - r.GlideDeg) < 0.1 && Math.Abs(t.TrimStick - r.TrimStick) < 0.01,
                $"{r.Id} flaps {r.Flaps}: the table is stale (table {t.SpeedKt:F1} kt {t.GlideDeg:F2}° trim {t.TrimStick:F3}, now {r.SpeedKt:F1} kt {r.GlideDeg:F2}° trim {r.TrimStick:F3}) — regenerate");
            _o.WriteLine($"{r.Id,-26} flaps {r.Flaps:F1}: Vso {r.VsoKt,4:F0} kt  1.3Vso {r.SpeedKt,4:F0} kt  glide {r.GlideDeg,4:F1}° ({r.GlideRatio:F1}:1)  sink {r.SinkFpm,5:F0} fpm  trim {r.TrimStick:+0.00;-0.00}");
        }
    }

    /// <summary>The new-airplane protocol's automated gate: every aircraft in configs/ must pass.</summary>
    [Fact]
    public void EveryAircraftPassesTheNewAirplaneProtocol()
    {
        string sa = Path.Combine(Repo, "unity", "Assets", "StreamingAssets", "aircraft");
        foreach (AircraftConfig c in All())
        {
            string file = Path.Combine(Repo, "configs", "aircraft", c.Id + ".json");
            Assert.True(File.Exists(file), $"{c.Id}: the file name must be the id");
            Assert.False(string.IsNullOrWhiteSpace(c.DisplayName), $"{c.Id}: display name");
            Assert.True(c.Mass.MassKg > 50, $"{c.Id}: mass");
            Assert.True(File.Exists(Path.Combine(sa, c.Id + ".json")) && File.ReadAllText(Path.Combine(sa, c.Id + ".json")) == File.ReadAllText(file),
                $"{c.Id}: StreamingAssets copy missing or different — copy configs/aircraft/{c.Id}.json into unity/Assets/StreamingAssets/aircraft/");
            double v = c.SpawnIasMs > 1 ? c.SpawnIasMs : 25;
            var trim = FlyingGame.Sim.TrimSolver.SolveGliderTrim(c, v, 300);
            Assert.True(trim.Converged, $"{c.Id}: does not trim at its spawn speed");
            double vso = PracticeScenario.EstimateVso(c, 0);
            Assert.True(vso / v > 0.3 && vso / v < 0.95, $"{c.Id}: Vso {vso * 1.944:F0} kt against spawn {v * 1.944:F0} kt");
            foreach (double f in GlideTable.FlapSettings(c))
            {
                var g = GlideTable.Compute(c, f);
                Assert.True(g.GlideRatio > (c.Propulsion == null ? 6 : 3) && g.GlideRatio < 60, $"{c.Id} flaps {f}: idle glide {g.GlideRatio:F1}:1 (gliders at half spoiler)");
                Assert.True(Math.Abs(g.TrimStick) < 1.0, $"{c.Id} flaps {f}: cannot trim the idle glide (stick {g.TrimStick:F2})");
            }
        }
    }
}
