<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FlyingGame.Sim</RootNamespace>
    <AssemblyName>FlyingGame.Sim</AssemblyName>
    <BaseIntermediateOutputPath>obj~/</BaseIntermediateOutputPath>
    <BaseOutputPath>bin~/</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FlyingGame.Core\FlyingGame.Core.csproj" />
  </ItemGroup>
</Project>
